package it.adesso.awesomepizza.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusAllPropertiesEquals(OrderStatus expected, OrderStatus actual) {
        assertOrderStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusAllUpdatablePropertiesEquals(OrderStatus expected, OrderStatus actual) {
        assertOrderStatusUpdatableFieldsEquals(expected, actual);
        assertOrderStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusAutoGeneratedPropertiesEquals(OrderStatus expected, OrderStatus actual) {
        assertThat(expected)
            .as("Verify OrderStatus auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusUpdatableFieldsEquals(OrderStatus expected, OrderStatus actual) {
        assertThat(expected)
            .as("Verify OrderStatus relevant properties")
            .satisfies(e -> assertThat(e.getStatusName()).as("check statusName").isEqualTo(actual.getStatusName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusUpdatableRelationshipsEquals(OrderStatus expected, OrderStatus actual) {
        // empty method
    }
}
