package it.adesso.awesomepizza.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PizzaMenuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPizzaMenuAllPropertiesEquals(PizzaMenu expected, PizzaMenu actual) {
        assertPizzaMenuAutoGeneratedPropertiesEquals(expected, actual);
        assertPizzaMenuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPizzaMenuAllUpdatablePropertiesEquals(PizzaMenu expected, PizzaMenu actual) {
        assertPizzaMenuUpdatableFieldsEquals(expected, actual);
        assertPizzaMenuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPizzaMenuAutoGeneratedPropertiesEquals(PizzaMenu expected, PizzaMenu actual) {
        assertThat(expected)
            .as("Verify PizzaMenu auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPizzaMenuUpdatableFieldsEquals(PizzaMenu expected, PizzaMenu actual) {
        assertThat(expected)
            .as("Verify PizzaMenu relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPizzaMenuUpdatableRelationshipsEquals(PizzaMenu expected, PizzaMenu actual) {
        // empty method
    }
}
